import React from 'react';
import { Page, Text, View, Document, StyleSheet, pdf } from '@react-pdf/renderer';
import { saveAs } from 'file-saver';
import { db } from './db';

// Define Styles
const styles = StyleSheet.create({
    page: { padding: 30, backgroundColor: '#ffffff' },
    header: { fontSize: 24, marginBottom: 10, textAlign: 'center', fontWeight: 'bold' },
    section: { margin: 10, padding: 10, flexGrow: 1 },
    title: { fontSize: 18, marginBottom: 5, borderBottom: '1px solid #ccc' },
    text: { fontSize: 12, marginBottom: 2 },
    row: { flexDirection: 'row', borderBottom: '1px solid #eee', paddingVertical: 2 },
    col1: { width: '60%' },
    col2: { width: '20%', textAlign: 'right' },
    col3: { width: '20%', textAlign: 'right' },
    footer: { position: 'absolute', bottom: 30, left: 30, right: 30, textAlign: 'center', fontSize: 10, color: '#888' }
});

// PDF Component
const ProjectDossier = ({ project, tasks, bom }: { project: any, tasks: any[], bom: any[] }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.section}>
                <Text style={styles.header}>{project.title}</Text>
                <Text style={{ textAlign: 'center', fontSize: 10, color: '#666', marginBottom: 20 }}>
                    Status: {project.status.toUpperCase()} | Priority: {project.priority}/5
                </Text>

                <Text style={styles.title}>Description</Text>
                <Text style={styles.text}>{project.status_description || 'No description provided.'}</Text>

                <Text style={{ ...styles.title, marginTop: 20 }}>Bill of Materials</Text>
                <View style={{ marginBottom: 10 }}>
                    <View style={{ flexDirection: 'row', borderBottom: '2px solid #000', paddingBottom: 2 }}>
                        <Text style={{ ...styles.col1, fontWeight: 'bold' }}>Item Name</Text>
                        <Text style={{ ...styles.col2, fontWeight: 'bold' }}>Qty</Text>
                        <Text style={{ ...styles.col3, fontWeight: 'bold' }}>Status</Text>
                    </View>
                    {bom.map((item, i) => (
                        <View key={i} style={styles.row}>
                            <Text style={styles.col1}>{item.name}</Text>
                            <Text style={styles.col2}>{item.quantity}</Text>
                            <Text style={styles.col3}>{item.status}</Text>
                        </View>
                    ))}
                </View>

                <Text style={{ ...styles.title, marginTop: 20 }}>Task Manifest</Text>
                {tasks.map((task, i) => (
                    <Text key={i} style={styles.text}>[ {task.status === 'completed' ? 'X' : ' '} ] {task.title}</Text>
                ))}
            </View>
            <Text style={styles.footer}>Generated by Antigravity Project Manager</Text>
        </Page>
    </Document>
);

export const ReportService = {
    async generateDossier(projectId: number) {
        const project = await db.projects.get(projectId);
        if (!project) throw new Error("Project not found");

        const tasks = await db.project_tasks.where({ project_id: projectId }).toArray();
        const bom = await db.project_bom.where({ project_id: projectId }).toArray();

        // Generate Blob
        const blob = await pdf(<ProjectDossier project={project} tasks={tasks} bom={bom} />).toBlob();

        // Save
        const filename = `${project.title.replace(/[^a-z0-9]/gi, '_')}_Dossier.pdf`;
        saveAs(blob, filename);

        return { success: true, filename };
    }
};
